-- Users
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'User',
    avatar_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- Items
CREATE TABLE IF NOT EXISTS public.items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Refresh tokens (rotation + revoke)
CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    jti TEXT UNIQUE NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tests (
    id BIGSERIAL PRIMARY KEY,
    result_id BIGSERIAL UNIQUE,
    test_name TEXT NOT NULL,
    test_category TEXT NOT NULL,
    test_price INT NOT NULL,
    test_ask INT NOT NULL,
    test_status BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.users_order (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    order_id VARCHAR NOT NULL UNIQUE
);




-- Helpful extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;